artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: covtype.zip
  local_data_file: artifacts/data_ingestion/covtype.zip
  unzip_dir: artifacts/data_ingestion/raw_data